AllCops:
  TargetRubyVersion: 2.3
  Exclude:
      - 'db/*'
      - 'vendor/ruby/**/*'
      - 'db/**/*'
      - 'config/*'
      - 'config/environments/*'
      - 'config/initializers/*'
      - 'Gemfile'
      - 'Guardfile'
      - 'bin/*'
      - 'lib/extensions/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
Style/StringLiterals:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Max: 30
